### PR TITLE
feat: http byte range support

### PR DESCRIPTION
**Pull request by alanshaw**
Adds HTTP byte range support for UnixFS files.

### CODE REVIEW

**Review by hannahhoward — APPROVED** [review]
Nice. Just curious -- technically I thinkRange supposed to work for suffix without a total length. Not super duper important -- you could just sub entry.size if it's not given. Also technically range supports multiple -- I think only supporting one is useful.

**Comment by hannahhoward** [comment]
Assume we built range support for trustless?

**Comment by alanshaw** [comment]
Suffix support is in there!

Range support was already in `ipfs-unixfs-exporter` - we built range support for trustless gateway (dagula implements this) but this is not used here.

**Comment by alanshaw** [comment]
closes https://github.com/storacha/gateway-lib/issues/12

**Pull request merged**
